name: Test builds

on:
  push:
  pull_request:

jobs:
  test:
    name: ${{matrix.rust}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-latest, windows-latest]
        rust:
          - 1.75.0
          - 1.63.0
          - stable
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Reset toolchain
        run: rm -f rust-toolchain.toml
        shell: bash

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
          components: clippy

      - name: Build
        run: cargo build

      - name: Unit-test
        run: cargo test

      - name: Analyze
        run: cargo clippy

      - name: Install test deps
        run: sudo apt install -y --no-install-recommends bats
        if: runner.os == 'Linux'

      - name: Install wine test deps on 1.75 and before
        run: sudo apt install -y --no-install-recommends mingw-w64 wine64 wine && rustup target add x86_64-pc-windows-gnu
        if: runner.os == 'Linux' && matrix.rust != 'stable'

      - name: Bypass wine tests after 1.75
        run: rm -f tests/wine.bats
        if: runner.os == 'Linux' && matrix.rust == 'stable'

      - name: Run CLI test
        run: bats ./tests
        if: runner.os == 'Linux'
